const http = require('http');

// Test data for Singapore trip
const tripData = {
  destination: "Singapore",
  startDate: "2025-08-15",
  endDate: "2025-08-20",
  budget: 2200,
  travelers: 2,
  interests: ["food", "culture", "shopping"],
  preferences: "Modern city with great food scene"
};

const data = JSON.stringify(tripData);

const options = {
  hostname: 'localhost',
  port: 3001,
  path: '/api/itinerary',
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'Content-Length': data.length
  }
};

console.log('🧪 Testing AI Trip Planner API');
console.log('=' .repeat(40));
console.log('📡 Sending request to API...');

const req = http.request(options, (res) => {
  let responseData = '';
  
  res.on('data', (chunk) => {
    responseData += chunk;
  });
  
  res.on('end', () => {
    try {
      const itinerary = JSON.parse(responseData);
      console.log('✅ API call successful!');
      console.log(`\n📍 Destination: ${itinerary.destination || 'N/A'}`);
      console.log(`📅 Duration: ${itinerary.duration || 'N/A'} days`);
      console.log(`💰 Estimated Budget: $${itinerary.estimatedBudget || 'N/A'}`);
      console.log(`🤖 Generated by: ${itinerary.generatedBy || 'N/A'}`);
      console.log(`🆔 Itinerary ID: ${itinerary.id || 'N/A'}`);
      
      // Show first day activities
      if (itinerary.dailyPlans && itinerary.dailyPlans.length > 0) {
        const firstDay = itinerary.dailyPlans[0];
        console.log(`\n📋 Day 1 (${firstDay.date || 'N/A'}) Activities:`);
        const activities = firstDay.activities || [];
        activities.slice(0, 2).forEach(activity => {
          console.log(`  • ${activity.time || 'N/A'}: ${activity.name || 'N/A'}`);
        });
      }
      
      console.log('\n🎉 API test completed successfully!');
      console.log('\n✅ The AI Trip Planner agent is working correctly!');
    } catch (error) {
      console.error('❌ Failed to parse API response:', error.message);
      console.log('Raw response:', responseData);
    }
  });
});

req.on('error', (error) => {
  console.error('❌ API test failed:', error.message);
});

req.write(data);
req.end();