#!/usr/bin/env python3
"""
Simple API test for the AI Trip Planner
"""

import requests
import json
import time

def test_api():
    """Test the API endpoint"""
    print("🧪 Testing AI Trip Planner API")
    print("=" * 40)
    
    # Test data
    trip_data = {
        "destination": "Singapore",
        "startDate": "2025-08-15",
        "endDate": "2025-08-20",
        "budget": 2200,
        "travelers": 2,
        "interests": ["food", "culture", "shopping"],
        "preferences": "Modern city with great food scene"
    }
    
    try:
        print("📡 Sending request to API...")
        response = requests.post(
            'http://localhost:3001/api/itinerary',
            json=trip_data,
            headers={'Content-Type': 'application/json'},
            timeout=30
        )
        
        if response.status_code == 200:
            print("✅ API call successful!")
            itinerary = response.json()
            
            print(f"\n📍 Destination: {itinerary.get('destination', 'N/A')}")
            print(f"📅 Duration: {itinerary.get('duration', 'N/A')} days")
            print(f"💰 Estimated Budget: ${itinerary.get('estimatedBudget', 'N/A')}")
            print(f"🤖 Generated by: {itinerary.get('generatedBy', 'N/A')}")
            print(f"🆔 Itinerary ID: {itinerary.get('id', 'N/A')}")
            
            # Show first day activities
            daily_plans = itinerary.get('dailyPlans', [])
            if daily_plans:
                first_day = daily_plans[0]
                print(f"\n📋 Day 1 ({first_day.get('date', 'N/A')}) Activities:")
                for activity in first_day.get('activities', [])[:2]:  # Show first 2 activities
                    print(f"  • {activity.get('time', 'N/A')}: {activity.get('name', 'N/A')}")
            
            print("\n🎉 API test completed successfully!")
            return True
        else:
            print(f"❌ API call failed with status: {response.status_code}")
            print(f"Response: {response.text}")
            return False
            
    except requests.exceptions.RequestException as e:
        print(f"❌ API test failed: {e}")
        return False

if __name__ == "__main__":
    success = test_api()
    if success:
        print("\n✅ The AI Trip Planner agent is working correctly!")
    else:
        print("\n❌ There were issues with the API test.")